name: Python Testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test_pykokkos:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - if: ${{matrix.platform == 'macos-latest'}}
        name: Install MacOS deps
        run: |
          brew install automake patchelf
      - if: ${{matrix.platform == 'ubuntu-latest'}}
        name: Install Linux deps
        run: |
          python -m pip install patchelf
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy mypy cmake pytest pybind11 scikit-build
      - if: ${{matrix.platform == 'macos-latest'}}
        name: Install pykokkos-base on MacOS
        run: |
          cd /tmp
          git clone https://github.com/kokkos/pykokkos-base.git
          cd pykokkos-base
          python setup.py install -- -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF -DKokkos_ENABLE_OPENMP=OFF
      - if: ${{matrix.platform == 'ubuntu-latest'}}
        name: Install pykokkos-base on Linux
        run: |
          cd /tmp
          git clone https://github.com/kokkos/pykokkos-base.git
          cd pykokkos-base
          python setup.py install -- -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF
      - name: Install pykokkos
        run: |
          python -m pip install .
      - name: mypy check
        run: |
          mypy pykokkos
      - name: run tests
        run: |
          python runtests.py
