name: Python Testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test_pykokkos:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10.6", "3.11.0-rc.1"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy mypy cmake pytest pybind11 scikit-build patchelf pytest-cov codecov
      - name: Install pykokkos-base
        run: |
          cd /tmp
          git clone https://github.com/kokkos/pykokkos-base.git
          cd pykokkos-base
          python setup.py install -- -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF
      - name: Install pykokkos
        run: |
          python -m pip install .
      - name: mypy check
        run: |
          mypy pykokkos
      - name: run tests
        run: |
          python runtests.py --coverage
      - name: codecov check
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: False
